### ISSUE TITLE
Kinect overrides other cameras

### ISSUE THREAD

**Issue by Wrathicus** [sheepsskullcity/opentrackkinect#1]
It's pretty much as the title says. The tracking is spectacular, but it kind of falls short if there's no way to use any sort of  motion controller (other than the Hydras / Vive controllers). I'm trying to use PSMoveService, but whenever I start the tool for the Kinect tracking it just dominates the others and basically shuts them down.

I have no knowledge of these sort of things. This is mostly just a request to see if there was a way around it.

Edit: Guess it doesn't dominate other cameras, just keeps any other cameras from being on the USB 3.0 ports. Food for thought. :X

**Comment by sheepsskullcity** [comment]
Can you use this tool for screenshot [usbtreeview](http://www.uwe-sieber.de/usbtreeview_e.html) ?
